name: Compile Python to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 可以根据需要选择Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compile Python to EXE
      run: |
        pyinstaller --onefile your_script.py  # 将your_script.py替换为你的Python脚本文件名

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-exe
        path: dist/stealer  # 将your_script替换为你的Python脚本文件名（不带扩展名）
