name: Compile Python to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Compile Python to EXE
        run: |
          pyinstaller --onefile stealer.py  # 请将 main.py 替换为你实际的 Python 文件名

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exe
          path: dist/stealer  # 请将 main 替换为编译后生成的文件名称（不带扩展名）
