name: Compile Python to EXE and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies and PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Compile Python to EXE
        run: |
          pyinstaller --onefile a.py
          # 默认生成的 EXE 文件位于 dist 文件夹内，文件名与脚本名称相同，此处应为 a.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exe
          path: dist/a.exe
